apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oli6pnroq-java-springboot 
  janus-idp.io/tekton: oli6pnroq-java-springboot
  backstage.io/kubernetes-id: oli6pnroq-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oli6pnroq-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml